# Generated by Django 5.1.4 on 2025-01-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTAPI', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
